services:
 web:
  build: .
  command: npm start
  volumes:
   - .:/usr/app/
   - /usr/app/node_modules
  ports:
   - 5000:5000
  depends_on:
   - postgres
#  environment:
#   DATABASE_URL: postgres://testDB@postgres/todos
 postgres:
  ports:
   - 5433:5432
#  expose:
#  - 5433
#  - 5345
  image: postgres:latest
  environment:
   POSTGRES_PASSWORD: 'varofromdataart'
#   POSTGRES_USER: todoapp
#   POSTGRES_DB: todos
